[package]
name = "main_package"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
DepPackage = {local = "../dep_package"}

[addresses]
main_package =  "0x0"
# sui =  "0000000000000000000000000000000000000002"
